import type { LocalModelDefinition } from "./modelTypes";

export const localModelCatalog: readonly LocalModelDefinition[] = [
  {
    id: "qwen3-0.6b",
    displayName: "Qwen3-0.6B",
    family: "qwen3",
    parameterSize: "0.6B",
    recommendedLanguages: ["ru", "en"],
    tier: "very-fast-cpu",
    recommendedHardware: "cpu-low",
    runtime: "llama-cpp",
    availability: "catalog-only",
    notes: "Очень быстрый CPU-профиль для слабых ноутбуков.",
  },
  {
    id: "qwen3-1.7b",
    displayName: "Qwen3-1.7B",
    family: "qwen3",
    parameterSize: "1.7B",
    recommendedLanguages: ["ru", "en"],
    tier: "fast-cpu",
    recommendedHardware: "cpu-low",
    runtime: "llama-cpp",
    availability: "catalog-only",
    notes: "Быстрый CPU-профиль для локальных подсказок.",
  },
  {
    id: "ruadapt-qwen2.5-1.5b",
    displayName: "Ruadapt Qwen2.5 1.5B",
    family: "ruadapt-qwen2.5",
    parameterSize: "1.5B",
    recommendedLanguages: ["ru"],
    tier: "russian-cpu",
    recommendedHardware: "cpu-low",
    runtime: "llama-cpp",
    availability: "catalog-only",
    notes: "Русский текст на слабых ПК.",
  },
  {
    id: "ruadapt-qwen2.5-3b",
    displayName: "Ruadapt Qwen2.5 3B",
    family: "ruadapt-qwen2.5",
    parameterSize: "3B",
    recommendedLanguages: ["ru"],
    tier: "russian-cpu",
    recommendedHardware: "cpu",
    runtime: "llama-cpp",
    availability: "catalog-only",
    notes: "Русский текст на CPU.",
  },
  {
    id: "qwen3-4b",
    displayName: "Qwen3-4B",
    family: "qwen3",
    parameterSize: "4B",
    recommendedLanguages: ["ru", "en"],
    tier: "balanced",
    recommendedHardware: "cpu",
    isDefault: true,
    runtime: "llama-cpp",
    availability: "catalog-only",
    notes: "Модель по умолчанию для сбалансированного качества.",
  },
  {
    id: "qwen3-8b",
    displayName: "Qwen3-8B",
    family: "qwen3",
    parameterSize: "8B",
    recommendedLanguages: ["ru", "en"],
    tier: "quality",
    recommendedHardware: "gpu-or-strong-cpu",
    runtime: "llama-cpp",
    availability: "catalog-only",
    notes: "Профиль качества для GPU или сильного CPU.",
  },
];
